export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAILURE = "GET_PRODUCT_BY_ID_FAILURE";

export const ADD_PRODUCT_REQUEST  = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS  = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE  = "ADD_PRODUCT_FAILURE";

export const DELETE_PRODUCT_REQUEST  = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS  = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE  = "DELETE_PRODUCT_FAILURE";

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";